### ISSUE TITLE
TypeError: Odd-length string

### ISSUE THREAD

**Issue by JO-WTF** [OctavianLee/Barrage#15]
您所在直播间(Exit 退出助手)：92075
请求服务器连接
Traceback (most recent call last):
  File "main.py", line 6, in <module>
    hime = DanmakuHime()
  File "/Users/JOE/Downloads/Barrage-master-2/danmaku/hime.py", line 19, in **init**
    self.run()
  File "/Users/JOE/Downloads/Barrage-master-2/danmaku/hime.py", line 39, in run
    self.create_service(option, room_id)
  File "/Users/JOE/Downloads/Barrage-master-2/danmaku/hime.py", line 57, in create_service
    service.cmd_run()
  File "/Users/JOE/Downloads/Barrage-master-2/danmaku/services/reciever.py", line 18, in cmd_run
    run_recieve(self.room_id)
  File "/Users/JOE/Downloads/Barrage-master-2/danmaku/cores/socket_process.py", line 68, in run_recieve
    with generate_socket(room_id) as sock:
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in **enter**
    return self.gen.next()
  File "/Users/JOE/Downloads/Barrage-master-2/danmaku/cores/socket_process.py", line 31, in generate_socket
    send_data = unhexlify(data)
TypeError: Odd-length string

测试其他房间的时候没问题，不知道这个房间的问题是什么。

**Comment by superfashi** [comment]
这是b站服务器的锅，有的时候传回的数据根本都不出来，找个时间全expect一下……

**Comment by OctavianLee** [comment]
@hanbang-wang  这个 问题 应该不是 这个引起的，原先房间号没有那么大的，位置大的解析出来的 是 25位 unhexlify不能解析那么长，大房间处理上策略可能有所不同。

``` python
from binascii import unhexlify
unhexlify('0101000c0000167ab00000000') # 房间 92075
unhexlify('0101000c0000000100000000') # 房间1
```

这块需要查一下，b站那边只是做一层加密策略，我没有细研究过，这个问题先开吧

**Comment by OctavianLee** [comment]
@feisuzhu 之前我关注你也写了个这个，是没有遇到过这个情况吗，我好久没有花时间关注这块了

**Comment by OctavianLee** [comment]
@feisuzhu 我刚刚看了你这部分的处理，我打算参考你用struct的方式可以吗？

**Comment by superfashi** [comment]
@OctavianLee 不是unhexlify不能解析那么长，而是因为这是一个八位整数而不是四位……

**Comment by superfashi** [comment]
我还是直接帮你改了吧，当然用struct其实更好一点。

**Comment by OctavianLee** [comment]
@hanbang-wang 我看到了 是这样的，thx 我忘了当时这边设定是4了
