### ISSUE TITLE
[业务]友好的按键跳出

### ISSUE THREAD

**Issue by OctavianLee** [OctavianLee/Barrage#7]
目前没有争对处理KeybordError，因此需要添加进这个内容增强体验。

**Comment by planktonzp** [comment]
额，ctrl+C退出的时候总是跳一大段文件执行记录。。。看着有点不开心，系统:archlinux 老机器 如果有时间请回复

**Comment by planktonzp** [comment]
Traceback (most recent call last):
  File "main.py", line 6, in <module>
    hime = DanmakuHime()
  File "/home/roy/.virtualenv/Barrage/danmaku/hime.py", line 18, in **init**
    self.run()
  File "/home/roy/.virtualenv/Barrage/danmaku/hime.py", line 38, in run
    self.create_service(option, room_id)
  File "/home/roy/.virtualenv/Barrage/danmaku/hime.py", line 56, in create_service
    service.cmd_run()
  File "/home/roy/.virtualenv/Barrage/danmaku/services/reciever.py", line 18, in cmd_run
    run_recieve(self.room_id)
  File "/home/roy/.virtualenv/Barrage/danmaku/cores/socket_process.py", line 69, in run_recieve
    produce_danmaku.switch(sock, danmaku_queue, True)
  File "/home/roy/.virtualenv/Barrage/danmaku/cores/produce_and_consume.py", line 64, in consume_danmaku
    print danmaku
TypeError: **str** returned non-string (type NoneType)

**Comment by OctavianLee** [comment]
@ruizhipeng 刚刚看到，工作繁忙，有点懒，所以更新没那么频繁，下面抽时间来整理这个项目，毕竟自己直播还是会用到的。
